changelog:
  - version: Unreleased
    release_date: TBD
    security:
      - Update `dprint` to version `0.49.1`.
        ([#39](https://github.com/jelmore1674/build-changelog/pull/39)) ([Justin
        Elmore](https://github.com/jelmore1674))
      - Update `yaml` to `2.7.1`.
        ([#40](https://github.com/jelmore1674/build-changelog/pull/40)) ([Justin
        Elmore](https://github.com/jelmore1674))
  - version: 1.1.0
    release_date: 2025-04-02
    added:
      - Added `show_author` and `show_author_full_name` to the changelog
        configuration. ([Justin Elmore](https://github.com/jelmore1674))
      - Automatically reference `pull_request` number to the changelog entry.
        ([Justin Elmore](https://github.com/jelmore1674))
      - Commit and push using the Github Api.
        ([#25](https://github.com/jelmore1674/build-changelog/pull/25)) ([Justin
        Elmore](https://github.com/jelmore1674))
      - Commit and push using the git binary in the action.
        ([#25](https://github.com/jelmore1674/build-changelog/pull/25)) ([Justin
        Elmore](https://github.com/jelmore1674))
      - "`commit_with_api` input to choose between using binary or api to
        commit. ([#25](https://github.com/jelmore1674/build-changelog/pull/25))
        ([Justin Elmore](https://github.com/jelmore1674))"
      - Add input for `version` for setting the release version for unreleased
        changes. ([#34](https://github.com/jelmore1674/build-changelog/pull/34))
        ([Justin Elmore](https://github.com/jelmore1674))
      - Use inputs to configure the action instead of a configuration file.
        ([#38](https://github.com/jelmore1674/build-changelog/pull/38)) ([Justin
        Elmore](https://github.com/jelmore1674))
    changed:
      - Changed enforcer to call `generate` directly instead of relying on
        another action. ([Justin Elmore](https://github.com/jelmore1674))
      - Change to use `context.sha` to detect if pr has been merged. ([Justin
        Elmore](https://github.com/jelmore1674))
      - Update `enforcer` action to use `@actions/exec` instead of node's
        `execSync`.
        ([#24](https://github.com/jelmore1674/build-changelog/pull/24)) ([Justin
        Elmore](https://github.com/jelmore1674))
    removed:
      - Remove unused inputs from the project.
        ([#25](https://github.com/jelmore1674/build-changelog/pull/25)) ([Justin
        Elmore](https://github.com/jelmore1674))
    fixed:
      - Fixed `pull_request` auto referencing.
        ([#19](https://github.com/jelmore1674/build-changelog/pull/19)) ([Justin
        Elmore](https://github.com/jelmore1674))
      - Prevent `Enforcer` action from failing when running the generate
        command. ([#33](https://github.com/jelmore1674/build-changelog/pull/33))
        ([Justin Elmore](https://github.com/jelmore1674))
      - Remove the leading `v` from the version prefix when using the tag as
        input. ([#35](https://github.com/jelmore1674/build-changelog/pull/35))
        ([Justin Elmore](https://github.com/jelmore1674))
      - Fixes being able to set version and date of unreleased changes.
        ([#36](https://github.com/jelmore1674/build-changelog/pull/36)) ([Justin
        Elmore](https://github.com/jelmore1674))
  - version: 1.0.0
    release_date: 2025-03-20
    notice: Initial Release
