version = "0.4.0"
release_date = "2024-12-08"

[changed]
breaking = [
  "Renames `releaseDate` to `release_date`.",
  "Default option to parse changelog over keeping an archive.",
]
templates = [
  "Updated `guide.md` template.",
  "Added release linking to Changelog generation.",
]
config = [
  "Added `release_url`, `changelog_archive`, and `git_tag_prefix` to the configuration.",
]

[added]
feature = ["Parsing existing changelog file."]
