version = "1.0.0"
release_date = "2024-12-28"

[added]
feature = [
  "Now able to be used as an action. See (docs)[https://forgejo.justinelmore.dev/jelmore1674/build-changelog#actions]",
]

[security]
changes = [
  "pin depencies",
  "update vitest monorepo to v2.1.8",
  "update dependency vite-tsconfig-paths to v5.1.4",
  "update pnpm to v9.15.1",
  "update dependency dprint to v0.48.0",
  "update dependency typescript to v5.7.2",
  "update node.js to v22",
]
