name: Enforce Changelog
description: "Enforce your changelog"

inputs:
  skip_labels:
    default: "ops"
    description: "Comma separated list of labels to skip enforcing changelog changes."

  enable_dependabot:
    description: Allow creation of changelog file when dependabot creates a pull request.
    default: "false"
    required: false

  dependabot_labels:
    description: The labels you to activate dependabot changelog updates.
    default: ""
    required: false

  dependabot_section:
    description: The section to put the dependabot changes in. Can be either `security` or `changed`.
    default: "security"
    required: false

  show_author_full_name:
    description: Show the authors name instead of the authors username.
    default: "false"
    required: false

  name_override:
    description: |
      If you have a naming that you want to use that is not the github username, then you can
      override the github username. Must use a `key=value` pair comma separated.
    required: false

  custom_bot_name:
    description: |
      If you have to use a different token other than the default, pass in the name of bot to be
      able to find existing comments. Example. `github-actions[bot]`. Currently this only looks for
      a bot user type.
    required: false

  comment_on_pr:
    description: |
      The bot will leave a comment with a preview of the changes, if the enforce action fails it
      will tag the user and let them know the action failed
    default: "false"
    required: false

  token:
    description: "The secret value from your GITHUB_TOKEN or another token to access the GitHub API. Defaults to the token at `github.token`"
    required: true
    default: ${{ github.token }}

runs:
  using: node20
  main: index.js
  post: index.js
