name: Build Changelog Action
description: Generate your changelog from your changelog files.
author: Justin Elmore

inputs:
  commit_with_api:
    description: Use the GitHub api to generate a signed commit. However, you cannot force push and this will be a new commit.
    default: "true"
    required: false

  release_type:
    description: The semantic version change type. Accepted values are major, minor, patch
    required: false

  dir:
    description: The directory to keep your changelog files. Defaults to the `changelog` directory.
    default: "changelog"
    required: true

  flags:
    description: Any custom flags with prefixes. Ex. `[Breaking 🧨]` for breaking changes. Must use a key=value pair comma separated list no spaces.
    default: "breaking=[Breaking 🧨]"
    required: false

  show_author:
    description: Reference the author in the changelog entry.
    default: "true"
    required: false

  show_author_full_name:
    description: Show the authors name instead of the authors username.
    default: "false"
    required: false

  git_tag_prefix:
    description: The prefix for your git tags.
    default: "v"
    required: true

  reference_pull_requests:
    description: Automatically reference pull requests when you merge changes in.
    default: "true"
    required: false

  version:
    description: Set the version of the unreleased changes.
    required: false

  commit_user_name:
    description: The committer user name. Defaults to `github-actions[bot]`.
    default: github-actions[bot]
    required: false

  commit_user_email:
    description: The committer email. Defaults to `41898282+github-actions[bot]@users.noreply.github.com`.
    default: 41898282+github-actions[bot]@users.noreply.github.com
    required: false

  commit_author:
    description: The commit author. Defaults to the use who triggered the action.
    required: false
    default: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>

  commit_message:
    description: The commit message.
    default: Update CHANGELOG.
    required: false

  commit_options:
    description: Commit options (ex. --amend)
    required: false
    default: ""

  push_options:
    description: Push options (ex. --force)
    required: false
    default: ""

  token:
    description: The secret value from your GITHUB_TOKEN or another token to access the GitHub API. Defaults to the token at `github.token`
    required: true
    default: ${{ github.token }}

outputs:
  notes:
    description: "The Release Notes for the latest changes."

runs:
  using: node20
  main: ./generate/index.js
