dir = "changelog"
prefers = "toml"
git_tag_prefix = "v"
changelog_archive = true
release_url = "https://gitlab.justinelmore.dev/jelmore1674/build-changelog/-/releases"

[flags]
breaking = "[Breaking 🧨]"
