name: Build & Test

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "**/build.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install Packages.
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
