name: Build & Test

on:
  push:
    paths:
      - "src/*"
      - "package.json"
      - "pnpm-lock.yaml"
      - "**/build.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v4
      - uses: https://github.com/pnpm/action-setup@v4
      - uses: https://github.com/actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install Packages.
        run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
