name: Changelog

on:
  push:
    branches:
      - main
    paths:
      - "changelog/*"
      - "bcl.toml"
      - "**/changelog.yml"

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"
          cache: "pnpm"

      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: npm i -g .
      - run: bcl generate

      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GPG_KEY: op://Forgejo/ENV/GPG_KEY
          GPG_PASSPHRASE: op://Forgejo/ENV/GPG_PASSPHRASE

      - name: decode gpg
        id: decode
        run: |
          KEY=$(echo "${{ steps.load-op.outputs.GPG_KEY }}" | base64 -d) && \
          cat >> $GITHUB_OUTPUT <<EOF
          GPG<<STRING
          $KEY
          STRING
          EOF

      - name: "Import GPG key"
        id: import-gpg
        uses: https://github.com/crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6
        with:
          gpg_private_key: ${{ steps.decode.outputs.GPG }}
          passphrase: "${{ steps.load-op.outputs.GPG_PASSPHRASE }}"
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: "Commit and push changes"
        uses: https://github.com/stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_author: "${{ steps.import-gpg.outputs.name }} <${{ steps.import-gpg.outputs.email }}>"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_message: "chore: Update CHANGELOG.md"
