name: deploy

on:
  push:
    tags:
      - "v*"

  release:
    types: [published]

  workflow_dispatch:

jobs:
  build-npm:
    name: build-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Load ENV from 1Password
        uses: 1password/load-secrets-action@581a835fb51b8e7ec56b71cf2ffddd7e68bb25e0 # v2
        id: load-op
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ACTION_TOKEN: op://Forgejo/ENV/ACTION_TOKEN

      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm i --frozen-lockfile
      - run: pnpm build

      - name: publish npm
        uses: https://github.com/JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3
        with:
          token: ${{ steps.load-op.outputs.ACTION_TOKEN }}
          registry: "${{ env.NPM_REGISTRY_URL }}/${{ env.GITHUB_REPOSITORY_OWNER}}/npm"
