name: changelog-action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GPG_KEY: op://Forgejo/ENV/GPG_KEY
          GPG_PASSPHRASE: op://Forgejo/ENV/GPG_PASSPHRASE

      - name: decode gpg
        id: decode
        run: |
          KEY=$(echo "${{ steps.load-op.outputs.GPG_KEY }}" | base64 -d) && \
          cat >> $GITHUB_OUTPUT <<EOF
          GPG<<STRING
          $KEY
          STRING
          EOF

      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - name: Generate Changelog
        uses: ./
        with:
          gpg_private_key: ${{ steps.decode.outputs.GPG }}
          passphrase: "${{ steps.load-op.outputs.GPG_PASSPHRASE }}"
          commit_user_name: ${{ steps.import-gpg.outputs.name }}
          commit_user_email: ${{ steps.import-gpg.outputs.email }}
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: "--amend"
          push_options: "--force"
