name: changelog-action

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load secret
        id: load-op
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GPG_KEY: op://Forgejo/ENV/GPG_KEY
          GPG_PASSPHRASE: op://Forgejo/ENV/GPG_PASSPHRASE

      - name: decode gpg
        id: decode
        run: |
          KEY=$(echo "${{ steps.load-op.outputs.GPG_KEY }}" | base64 -d) && \
          cat >> $GITHUB_OUTPUT <<EOF
          GPG<<STRING
          $KEY
          STRING
          EOF

      - name: Generate Changelog
        uses: ./
        with:
          commit_message: "chore: Update CHANGELOG.md"
