name: Changelog

on:
  workflow_dispatch:
  push:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Generate Changelog
        uses: ./
        with:
          show_author_full_name: true
          changelog_style: common-changelog
          show_git_tag_prefix: true
          skip_commit: true
