name: Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "changelog/*"
      - "bcl.toml"
      - "**/changelog.yml"
      - "CHANGELOG.md"

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Generate Changelog
        uses: ./generate

      - name: Commit and Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit --amend --no-edit
          git push origin HEAD
