name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        type: "string"
        default: "v"
        required: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_NOTES: "${{ steps.release-notes.outputs.RELEASE_NOTES }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set Version for Unreleased
        uses: ./
        with:
          version: ${{ inputs.tag }}

      - name: Get Latest Sha
        id: sha
        run: |
          git pull origin HEAD
          echo "sha=$(git rev-parse HEAD)"  >> "$GITHUB_OUTPUT"

      - name: Get Release Notes
        id: release-notes
        uses: ./notes

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          NOTES: ${{ steps.release-notes.outputs.notes }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          commitish: ${{ steps.sha.outputs.sha }}
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          body: ${{ env.NOTES }}
          draft: false
          prerelease: false
