name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        type: "string"
        default: "v"
        required: true
      override:
        description: "Override Existing Release"
        type: boolean
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_NOTES: "${{ steps.release-notes.outputs.RELEASE_NOTES }}"
    steps:
      - uses: actions/checkout@v4

      - name: Get Release Notes
        id: release-notes
        uses: ./notes

      - uses: 1password/load-secrets-action@v2
        id: load-op
        with:
          # Export loaded secrets as environment variables
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          ACTION_TOKEN: op://Forgejo/ENV/ACTION_TOKEN

      - uses: https://gitea.justinelmore.dev/actions/release@v2.6.1
        env:
          RELEASE_NOTES: ${{ steps.release-notes.outputs.notes }}
        with:
          direction: upload
          url: https://gitea.justinelmore.dev
          release-notes: ${{ env.RELEASE_NOTES }}
          tag: ${{ inputs.tag }}
          token: ${{ steps.load-op.outputs.ACTION_TOKEN }}
          verbose: true
          override: ${{ inputs.override }}
