name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The semver release type
        type: choice
        default: patch
        required: true
        options:
          - patch
          - minor
          - major

      tag:
        description: Release Tag
        type: string
        required: false

      release_name:
        description: The release name.
        type: string
        required: false

      update_package_json:
        description: Update the package.json version.
        type: boolean
        default: true

      move_major_version_tag:
        description: Move the major version tag.
        type: boolean
        default: true

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the
  # added or changed files to the repository.
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Version for Unreleased
        id: changelog
        uses: ./
        with:
          version: ${{ inputs.tag }}

      - name: Create Release
        id: create_release
        uses: jelmore1674/release-semver-action@v2
        with:
          commitish: ${{ steps.sha.outputs.sha }}
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          body: ${{ steps.changelog.outputs.notes }}
          draft: false
          prerelease: false
